//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStore.DAL.EF
{
    using System;
    using System.Collections.Generic;
    using PhoneStore.Models;
    using PhoneStore.BL.Service;

    public partial class ImageEntity : IStorageModel<Image>
    {
        public int ID { get; set; }
        public string Image { get; set; }
        public int PhoneId { get; set; }

        public virtual PhoneEntity Phones { get; set; }

        public Image ConvertToApplicationModel()
        {
            Image image = new Image()
            {
                ID = this.ID,
                ImageURL = this.Image,
                PhoneId = this.PhoneId
            };
            return image;
        }

        public IStorageModel<Image> FromApplicationModel(Image model)
        {
            if (model == null)
                return null;
            ImageEntity imageEntity = new ImageEntity()
            {
                ID = model.ID,
                Image = model.ImageURL,
                PhoneId = model.PhoneId                
            };
            return imageEntity;
        }
    }
}
